site_name: Pydantic-redis
site_description: Pydantic-redis, simple declarative ORM for redis
site_url: https://sopherapps.github.io/pydantic-redis/

theme:
  name: material
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link

plugins:
  - search
  - mkdocstrings

repo_name: sopherapps/pydantic-redis
repo_url: https://github.com/sopherapps/pydantic-redis

nav:
  - 'Pydantic-redis': index.md
  - Tutorials:
      - tutorials/intro.md
      - Synchronous API:
          - tutorials/synchronous/models.md
          - tutorials/synchronous/insert.md
          - tutorials/synchronous/update.md
          - tutorials/synchronous/delete.md
          - tutorials/synchronous/select.md
          - tutorials/synchronous/nested-models.md
          - tutorials/synchronous/list-of-nested-models.md
          - tutorials/synchronous/tuple-of-nested-models.md
      - Asynchronous API:
          - tutorials/asynchronous/models.md
  - 'Explanation':
      - explanation/why-use-orms.md
  - reference.md
  - change-log.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - mdx_include:
      base_path: docs
extra_css:
  - css/termynal.css
  - css/custom.css
extra_javascript:
  - js/termynal.js
  - js/custom.js